name: brew test-bot
on:
  push:
    branches: [main]
  pull_request:
permissions: {}
defaults:
  run:
    shell: /bin/zsh -efux --extended-glob --pipe-fail --warn-create-global {0}
jobs:
  test-bot:
    strategy:
      matrix:
        runner: [macos-26, macos-26-intel]
    runs-on: ${{matrix.runner}}
    permissions:
      actions: read
      checks: read
      contents: read
      pull-requests: read
    steps:
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@3cdb78d0f62ad29dd32de765782654f4eedea607 # 2026.08.31.1
      with:
        token: ${{github.token}}

    - name: Cache Homebrew Bundler RubyGems
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: ${{steps.set-up-homebrew.outputs.gems-path}}
        key: ${{matrix.runner}}-rubygems-${{steps.set-up-homebrew.outputs.gems-hash}}
        restore-keys: ${{matrix.runner}}-rubygems-

    - run: brew test-bot --only-cleanup-before

    - run: brew test-bot --only-setup

    - name: Resolve commit SHA being released
      id: mas-commit-sha
      run: |
        commit_sha="$(sed -n 's/.*revision: *"\([0-9a-f]\{7,40\}\)".*/\1/p' "$(brew formula mas)" | head -n1)"
        if [[ -z "${commit_sha}" ]]; then
          printf $'::error::Could not resolve commit SHA from formula\n' >&2
          exit 1
        fi
        printf 'commit_sha=%s\n' "${commit_sha}" >>"${GITHUB_OUTPUT}"

    - name: Obtain .xcode-version
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        repository: mas-cli/mas
        ref: ${{steps.mas-commit-sha.outputs.commit_sha}}
        sparse-checkout: .xcode-version
        sparse-checkout-cone-mode: false

    - name: Select Xcode version
      run: xcodes select

    - run: brew test-bot --only-tap-syntax

    - name: Build, test & modify bottle to be for oldest macOS version supported by the current platform
      if: github.event_name == 'pull_request'
      run: |
        brew test-bot --only-formulae
        autoload zmv
        zmv '(*)tahoe(*)' '$1ventura$2'
        sed -i '' s/tahoe/ventura/g *ventura.bottle.json

    - name: Upload bottles as artifact
      if: always() && github.event_name == 'pull_request'
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: bottles_${{matrix.runner}}
        path: '*.bottle.*'
